services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  web:
    build: .
    container_name: python_app
    command: ["tail", "-f", "/dev/null"]  # Use a non-executing command
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword  # Ensure this matches the MYSQL_ROOT_PASSWORD for MySQL
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql_data:
